# Unity Marketplace Configuration
# This file contains marketplace-specific settings and configurations

# Marketplace Application Settings
marketplace:
  name: "Unity Marketplace Demo"
  version: "1.0.0"
  description: "Example marketplace application showcasing Unity S3 modules"
  
  # Application URLs and endpoints
  endpoints:
    api_base_url: "https://api.marketplace.unity.example.com"
    web_base_url: "https://marketplace.unity.example.com"
    static_assets_url: "https://static.marketplace.unity.example.com"
    admin_panel_url: "https://admin.marketplace.unity.example.com"
  
  # Feature configurations
  features:
    user_uploads: true
    virus_scanning: true
    content_moderation: false
    search_functionality: false
    recommendation_engine: false
    analytics: true
    caching: true
    cdn: true
    multi_tenancy: false
    api_versioning: true

# Storage Configuration
storage:
  # User uploads bucket settings
  user_uploads:
    max_file_size_mb: 100
    allowed_file_types:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
      - "application/pdf"
      - "text/plain"
      - "application/zip"
    virus_scanning_enabled: true
    content_moderation_enabled: false
    
  # Marketplace data bucket settings
  data:
    backup_frequency: "daily"
    retention_policy: "7_years"
    encryption_type: "AES256"
    cross_region_replication: false
    
  # Static assets bucket settings
  static_assets:
    cache_control_max_age: 86400  # 1 day
    compression_enabled: true
    cloudfront_enabled: false

# Security Settings
security:
  # Authentication and authorization
  auth:
    provider: "cognito"
    multi_factor_auth: false
    session_timeout_minutes: 480  # 8 hours
    password_policy:
      min_length: 8
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_symbols: true
  
  # API security
  api:
    rate_limiting:
      requests_per_minute: 1000
      burst_capacity: 2000
    cors:
      allowed_origins:
        - "https://marketplace.unity.example.com"
        - "https://admin.marketplace.unity.example.com"
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Content-Type", "Authorization", "X-API-Key"]
      max_age_seconds: 3600
    
  # Data protection
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    pii_detection: false
    data_classification: "internal"

# Performance and Scaling
performance:
  # Caching configuration
  caching:
    redis_enabled: false
    cloudfront_enabled: false
    browser_caching_enabled: true
    api_response_caching: true
    cache_ttl_seconds: 300  # 5 minutes
  
  # Auto-scaling settings
  scaling:
    min_capacity: 1
    max_capacity: 10
    target_cpu_utilization: 70
    scale_out_cooldown: 300
    scale_in_cooldown: 300
  
  # Database settings
  database:
    connection_pooling: true
    max_connections: 100
    query_timeout_seconds: 30
    slow_query_threshold: 1000  # ms

# Monitoring and Alerting
monitoring:
  # CloudWatch settings
  cloudwatch:
    detailed_monitoring: true
    log_retention_days: 30
    custom_metrics: true
    
  # Alerting configuration
  alerts:
    email_notifications: true
    slack_notifications: false
    pagerduty_integration: false
    alert_thresholds:
      error_rate_percent: 5
      response_time_ms: 2000
      cpu_utilization_percent: 80
      memory_utilization_percent: 85
      disk_usage_percent: 90
  
  # Health checks
  health_checks:
    endpoint: "/health"
    interval_seconds: 30
    timeout_seconds: 5
    failure_threshold: 3
    success_threshold: 2

# Integration Settings
integrations:
  # External services
  external_services:
    virus_scanner:
      enabled: true
      service: "clamav"
      quarantine_infected_files: true
    
    analytics:
      enabled: true
      service: "cloudwatch"
      custom_events: true
    
    search:
      enabled: false
      service: "elasticsearch"
      index_prefix: "marketplace"
  
  # Webhook configurations
  webhooks:
    file_upload_completed: null
    user_registration: null
    payment_processed: null
    
  # API integrations
  apis:
    payment_gateway: null
    email_service: "ses"
    sms_service: null

# Environment-specific Overrides
environments:
  dev:
    # Development environment settings
    debug_mode: true
    verbose_logging: true
    performance:
      scaling:
        min_capacity: 1
        max_capacity: 2
    security:
      auth:
        session_timeout_minutes: 60  # Shorter for dev
    monitoring:
      cloudwatch:
        log_retention_days: 7  # Shorter retention for dev
        
  staging:
    # Staging environment settings
    debug_mode: false
    verbose_logging: true
    performance:
      scaling:
        min_capacity: 1
        max_capacity: 5
    security:
      auth:
        session_timeout_minutes: 240  # 4 hours
    monitoring:
      cloudwatch:
        log_retention_days: 14
        
  prod:
    # Production environment settings
    debug_mode: false
    verbose_logging: false
    performance:
      caching:
        cloudfront_enabled: true
        cache_ttl_seconds: 3600  # 1 hour
      scaling:
        min_capacity: 2
        max_capacity: 20
    security:
      auth:
        multi_factor_auth: true
        session_timeout_minutes: 480  # 8 hours
      data_protection:
        pii_detection: true
    monitoring:
      cloudwatch:
        log_retention_days: 90
        detailed_monitoring: true
      alerts:
        pagerduty_integration: true

# Cost Management
cost_management:
  # Budget settings
  budgets:
    monthly_budget_usd: 500
    alert_thresholds: [50, 75, 90, 100]  # Percentage of budget
    
  # Resource optimization
  optimization:
    s3_intelligent_tiering: true
    reserved_capacity: false
    spot_instances: false
    
  # Cost allocation tags
  cost_tags:
    - "Project"
    - "Environment" 
    - "Owner"
    - "CostCenter"
    - "Application"

# Backup and Disaster Recovery
backup:
  # Backup schedules
  schedules:
    database: "daily"
    user_uploads: "weekly"
    application_data: "daily"
    configuration: "daily"
  
  # Retention policies
  retention:
    daily_backups: 7
    weekly_backups: 4
    monthly_backups: 12
    yearly_backups: 7
  
  # Cross-region disaster recovery
  disaster_recovery:
    enabled: false
    backup_region: "us-east-1"
    rpo_hours: 24  # Recovery Point Objective
    rto_hours: 4   # Recovery Time Objective

# Compliance and Governance
compliance:
  # Regulatory requirements
  regulations:
    gdpr_compliance: false
    hipaa_compliance: false
    sox_compliance: false
    
  # Data governance
  data_governance:
    data_retention_policy: "7_years"
    data_classification_required: true
    audit_logging: true
    
  # Access controls
  access_controls:
    rbac_enabled: true
    principle_of_least_privilege: true
    regular_access_reviews: false

# Development and Testing
development:
  # Local development settings
  local_dev:
    mock_external_services: true
    seed_data_enabled: true
    debug_endpoints: true
    
  # Testing configuration
  testing:
    unit_tests_required: true
    integration_tests_required: true
    performance_tests_required: false
    security_tests_required: true
    
  # CI/CD settings
  cicd:
    automated_testing: true
    automated_deployment: true
    rollback_enabled: true
    blue_green_deployment: false